config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    # get 'news/index'
    # get 'news/new'
    # get 'news/edit'
    # get 'admins/index'

    resources :admins, only: [:index]

    resources :news, only: [:index, :new, :create, :edit, :update, :destroy]
  end
  
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  
  get 'news/index'
  get 'news/show'
  get 'rescude_cats/index'
  get 'contacts/new'
  get 'contacts/confirm'
  get 'contacts/done'
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :contacts, only: [:new, :create] do
    collection do
      post 'confirm'
      post 'back'
      get 'done'
    end
  end
end

app/models/news.rb
# == Schema Information
#
# Table name: news
#
#  id          :bigint           not null, primary key
#  description :string(255)      not null
#  publish     :boolean          default(FALSE), not null
#  title       :string(255)      not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  tag_id      :integer          not null
#  writer_id   :integer          not null
#
class News < ApplicationRecord
  belongs_to :tag
  belongs_to :writer
  has_one_attached :image

  validates :title, presence: { message: 'は１文字以上入力してください。' }
  validates :description, presence: { message: 'は１文字以上入力してください。' }
end

app/controllers/admin/news_controller.rb
class Admin::NewsController < Admin::Base
  before_action :set_select_collections, only: [:index, :new, :create, :edit, :update]

  def index
    query = params[:query]
    tag_id = params[:tag_id]

    @current_tag = tag_id
        
    # News.joins(:tags).select('tags.name').where('title LIKE ? and tag LIKE ? ', "%#{query}%", "%#{tag_id}%") :
    # Newsのtag_idがtagsのidと紐づいている。Newsには関連するテーブルの名前 + _idが必要。あとhas_manyとbelongs_to。joinsは必要ないのか
    if tag_id.present? && query.present?
      @news = News.where('title LIKE ? and tag_id = ? ', "%#{query}%", tag_id).order(created_at: :desc)
    else
      if query.present?
        @news = News.where('title LIKE ?', "%#{query}%").order(created_at: :desc)
      elsif tag_id.present?
        @news = News.where('tag_id = ?', tag_id).order(created_at: :desc)
      else
        @news = News.order(created_at: :desc)
      end
    end
  end

  def new
    @news = News.new
  end

  def create
    @news = News.new(news_params)

    if @news.save
      redirect_to admin_news_index_path, notice: '登録しました'
    else
      render :new
    end
  end

  def edit
    @news = News.find(params[:id])
  end

  def update
    @news = News.find(params[:id])
    if @news.update(news_params)
      redirect_to admin_news_index_path, notice: '更新しました'
    else
      render :edit
    end
  end

  def destroy
    news = News.find(params[:id])
    news.destroy!
    redirect_to admin_news_path, notice: '削除しました'
  end

  private

  def news_params
    params.require(:news).permit(:title, :description, :tag_id, :writer_id, :publish, :image)
  end

  # selectの値を渡すために、、（左側のnameが表示内容で右側のidがvalueになる
  def set_select_collections
    @tag_collections = Tag.all.map { |c| [ c.name, c.id ] }
    @writer_collections = Writer.all.map { |c| [ c.name, c.id ] }
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  def index
    tag_id = params[:tag_id]
    @news = tag_id.nil? ? News.where(publish: true) : News.where(tag_id: tag_id, publish: true)

    @tags = Tag.all
    @current_tag = tag_id
  end

  def show
    @news = News.find(params[:id])
  end
end

app/views/admin/news/edit.html.erb
<h1 class="my-6 text-3xl font-bold">News</h1>

<div class="bg-white py-4 px-8 mb-6 shadow rounded">
  <div class="mb-8 text-sm font-medium text-center text-gray-500 border-b border-gray-200 dark:text-gray-400 dark:border-gray-700">
    <ul class="flex flex-wrap">
      <li>
        <%= link_to '一覧', admin_news_index_path, class: "inline-block p-4 px-6 border-b-2 border-transparent rounded-t-lg hover:text-gray-600 hover:border-gray-300 dark:hover:text-gray-300" %>
      </li>
      <li>
        <%= link_to '新規作成', new_admin_news_path, class: "inline-block p-4 px-6 border-b-2 border-transparent rounded-t-lg hover:text-gray-600 hover:border-gray-300 dark:hover:text-gray-300" %>
      </li>
    </ul>
  </div>

  <%= render(Admin::News::FormComponent.new(model: @news, url: admin_news_path, tag_collections: @tag_collections, writer_collections: @writer_collections)) %>
</div>

app/views/admin/news/index.html.erb
<h1 class="my-6 text-3xl font-bold">News</h1>

<div class="bg-white py-4 px-8 mb-6 shadow rounded">
  <div class="mb-8 text-sm font-medium text-center text-gray-500 border-b border-gray-200 dark:text-gray-400 dark:border-gray-700">
    <ul class="flex flex-wrap">
      <li>
        <%= link_to '一覧', admin_news_index_path, class: "inline-block py-4 px-6 text-blue-600 border-b-2 border-blue-600 rounded-t-lg active dark:text-blue-500 dark:border-blue-500" %>
      </li>
      <li>
        <%= link_to '新規作成', new_admin_news_path, class: "inline-block p-4 px-6 border-b-2 border-transparent rounded-t-lg hover:text-gray-600 hover:border-gray-300 dark:hover:text-gray-300" %>
      </li>
    </ul>
  </div>

  <div class="flex justify-end my-8">
    <%= form_tag admin_news_index_path, method: 'get' do %>
      <label>タグ検索：</label>
      <%= select_tag :tag_id, options_for_select(@tag_collections, selected: @current_tag), {include_blank: "全て", class: "shadow appearance-none border rounded py-2 pl-3 pr-8 leading-tight focus:outline-none focus:shadow-outline"} %>
      <label class="ml-2">タイトル検索：</label>
      <%= text_field_tag :query, params[:query], class: "shadow appearance-none border rounded py-2 px-3 mr-4 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
      <%= submit_tag "検索", name: nil, class: "btn btn-outline btn-sm" %>
    <% end %>
  </div>

  <section class="pb-4 mb-4 border-b border-gray-100">
    <div class="grid grid-cols-[3rem_1fr_6rem_6rem_4rem_10rem_6rem] gap-4 items-center text-sm font-bold">
      <p>ID</p>
      <p>タイトル</p>
      <p>タグ</p>
      <p>記者</p>
      <p>状態</p>
      <p>サムネイル</p>
      <p>操作</p>
    </div>
  </section>

  <section class="max-h-[calc(100vh-414px)] overflow-y-scroll">
    <%= render(Utility::NoItemComponent.new()) unless @news.present? %>
    <ul>
      <% @news.each do |news| %>
        <li class="grid grid-cols-[3rem_1fr_6rem_6rem_4rem_10rem_6rem] gap-4 items-center mb-2 text-sm">
          <p><%= news.id %></p>
          <h5 class="line-clamp-2 font-bold"><%= news.title %></h5>
          <p><%= news.tag.name %></p>
          <p><%= news.writer.name %></p>
          <p><%= news.publish ? "公開" : "未公開" %></p>
          <figure>
            <% if news.image.attached? %>
              <%= image_tag news.image, class: 'w-40 h-20 object-cover rounded-md', alt: 'サムネイル画像' %>
            <% else %>
              <%= image_tag "/assets/news/#{news.id}.jpg", class: 'w-40 h-20 object-cover rounded-md', alt: 'サムネイル画像' %>
            <% end %>
          </figure>
          <div class="flex justify-evenly text-sm">
            <%= link_to '編集', edit_admin_news_path(news), class: 'btn btn-outline btn-info btn-xs text-white font-normal' %>
            <%= button_to '削除', admin_news_path(news), type: 'button', class: 'btn btn-outline btn-error btn-xs text-white font-normal', method: :delete, data: { turbo_confirm: '削除してよろしいですか' } %>
          </div>
        </li>
      <% end %>
    </ul>
  </section>
</div>

app/views/admin/news/new.html.erb
<h1 class="my-6 text-3xl font-bold">News</h1>

<div class="bg-white py-4 px-8 mb-6 shadow rounded">
  <div class="mb-8 text-sm font-medium text-center text-gray-500 border-b border-gray-200 dark:text-gray-400 dark:border-gray-700">
    <ul class="flex flex-wrap">
      <li>
        <%= link_to '一覧', admin_news_index_path, class: "inline-block p-4 px-6 border-b-2 border-transparent rounded-t-lg hover:text-gray-600 hover:border-gray-300 dark:hover:text-gray-300" %>
      </li>
      <li>
        <%= link_to '新規作成', new_admin_news_path, class: "inline-block py-4 px-6 text-blue-600 border-b-2 border-blue-600 rounded-t-lg active dark:text-blue-500 dark:border-blue-500" %>
      </li>
    </ul>
  </div>
  
  <%= render(Admin::News::FormComponent.new(model: @news, url: admin_news_index_path, tag_collections: @tag_collections, writer_collections: @writer_collections)) %>
</div>