config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    # get 'news/index'
    # get 'news/new'
    # get 'news/edit'
    # get 'admins/index'

    resources :admins, only: [:index]

    resources :news, only: [:index, :new, :create, :edit, :update, :destroy]
  end
  
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  
  get 'news/index'
  get 'news/show'
  get 'rescude_cats/index'
  get 'contacts/new'
  get 'contacts/confirm'
  get 'contacts/done'
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :contacts, only: [:new, :create] do
    collection do
      post 'confirm'
      post 'back'
      get 'done'
    end
  end
end

app/models/contact.rb
# == Schema Information
#
# Table name: contacts
#
#  id         :bigint           not null, primary key
#  name       :string(255)      not null
#  email      :string(255)      not null
#  subject    :string(255)      not null
#  message    :text(65535)      not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Contact < ApplicationRecord
    
    validates :name, presence: { message: 'は１文字以上入力してください。' }
    validates :email, presence: { message: 'は１文字以上入力してください。' }
    validates :subject, presence: { message: 'は１文字以上入力してください。' }
    validates :message, presence: { message: 'は１文字以上入力してください。' }

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
    @contact = Contact.new
  end

  # 入力内容確認時
  def confirm
    @contact = Contact.new(contact_params)
    if @contact.invalid?
      render :new, status: :unprocessable_entity

      # formに data: { turbo: false } をする場合は以下の手法（エラー文言はflashになる）
      # flash[:alert] = @contact.errors.full_messages.join(", ")
      # @contact = Contact.new
      # redirect_to action: :new
    end
  end

  # 戻る際
  def back
    @contact = Contact.new(contact_params)
    render :new
  end

  # 送信時
  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      ContactMailer.send_mail(@contact).deliver_now
      redirect_to done_contacts_path
    else
      flash[:alert] = @contact.errors.full_messages.join(", ")
      @contact = Contact.new
      render :new
    end
  end

  def done
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :email, :subject, :message)
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/confirm.html.erb
<div class="max-w-xl m-auto">
  <div class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
    <div class="mb-4">
      <p class='block text-gray-700 text-sm font-bold mb-1'>お名前</p>
      <p class="w-full py-2 px-3 text-gray-700 leading-tight"><%= @contact.name %></p>
    </div>

    <div class="mb-4">
      <p class='block text-gray-700 text-sm font-bold mb-1'>メールアドレス</p>
      <p class="w-full py-2 px-3 text-gray-700 leading-tight"><%= @contact.email %></p>
    </div>

    <div class="mb-4">
      <p class='block text-gray-700 text-sm font-bold mb-1'>件名</p>
      <p class="w-full py-2 px-3 text-gray-700 leading-tight"><%= @contact.subject %></p>
    </div>

    <div class="mb-6">
      <p class='block text-gray-700 text-sm font-bold mb-1'>メッセージ</p>
      <p class="w-full py-2 px-3 text-gray-700 leading-tight"><%= @contact.message %></p>
    </div>

    <div class="flex justify-end">
      <div class="mr-3">
        <%= form_with model: @contact, url: back_contacts_path, data: { turbo: false } do |f| %>
          <%= f.hidden_field :name %>
          <%= f.hidden_field :email %>
          <%= f.hidden_field :subject %>
          <%= f.hidden_field :message %>
          <%= f.submit '入力画面に戻る', class: "btn btn-outline" %>
        <% end %>
      </div>
      <div>
        <%= form_with model: @contact do |f| %>
          <%= f.hidden_field :name %>
          <%= f.hidden_field :email %>
          <%= f.hidden_field :subject %>
          <%= f.hidden_field :message %>
          <%= f.submit '送信', class: "btn btn-info text-white" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/contacts/done.html.erb
<div class="text-center">
  <p class="font-bold text-2xl mb-8">お問い合わせありがとうございました</p>
  <%= link_to 'トップにもどる', '/', class: "btn btn-outline" %>
</div>

app/views/contacts/new.html.erb
<div class="max-w-xl m-auto">
  <%= form_with model: @contact, url: confirm_contacts_path, data: { turbo: false }, class: 'bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4' do |f| %>
    <%= render(Utility::ErrorMessagesComponent.new(model: f.object)) %>
    
    <div class="mb-4">
      <%= render(Form::LabelComponent.new(form: f, name: :name, title: 'お名前', id: 'name')) %>
      <%= render(Form::TextInputComponent.new(form: f, name: :name, id: 'name', placeholder: 'ねこ 太郎')) %>
    </div>

    <div class="mb-4">
      <%= render(Form::LabelComponent.new(form: f, name: :email, title: 'メールアドレス', id: 'email')) %>
      <%= render(Form::EmailInputComponent.new(form: f, name: :email, id: 'email', placeholder: 'nekoneko@neko.com')) %>
    </div>

    <div class="mb-4">
      <%= render(Form::LabelComponent.new(form: f, name: :subject, title: '件名', id: 'subject')) %>
      <%= render(Form::TextareaComponent.new(form: f, name: :subject, id: 'subject')) %>
    </div>

    <div class="mb-6">
      <%= render(Form::LabelComponent.new(form: f, name: :message, title: 'メッセージ', id: 'message')) %>
      <%= render(Form::TextareaComponent.new(form: f, name: :message, id: 'message', size: '10x10')) %>
    </div>

    <div class="flex justify-end">
      <%= f.submit '入力内容確認', class: "bg-blue-500 hover:bg-blue-700 text-white py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
    </div>
  <% end %>
</div>